<?php

return [
    'module' => [
        'name' => 'erp',
        'display_name' => ['es' => 'ERP', 'en' => 'ERP'],
        'icon' => 'ti tabler-building',
        'color' => 'primary',
    ],
    'items' => [
        [
            'key' => 'dashboard',
            'title' => ['es' => 'Dashboard', 'en' => 'Dashboard'],
            'icon' => 'ti tabler-smart-home',
            'route' => 'erp.index',
            'permission' => 'access.erp',
        ],
        [
            'key' => 'pos',
            'title' => ['es' => 'Punto de Venta (POS)', 'en' => 'Point of Sale (POS)'],
            'icon' => 'ti tabler-cash-register',
            'permission' => 'erp.sales.view',
            'children' => [
                [
                    'key' => 'tickets-venta',
                    'title' => ['es' => 'Tickets de venta', 'en' => 'Sales Tickets'],
                    'icon' => 'ti tabler-receipt',
                    'route' => 'erp.pos.tickets.create',
                    'permission' => 'erp.sales.view',
                ],
                [
                    'key' => 'historial-tickets',
                    'title' => ['es' => 'Historial de tickets', 'en' => 'Ticket History'],
                    'icon' => 'ti tabler-history',
                    'route' => 'erp.pos.tickets.index',
                    'permission' => 'erp.sales.view',
                ],
                [
                    'key' => 'caja',
                    'title' => ['es' => 'Caja', 'en' => 'Cash Drawer'],
                    'icon' => 'ti tabler-cash',
                    'route' => 'erp.pos.cash.index',
                    'permission' => 'erp.sales.view',
                ],
                [
                    'key' => 'devoluciones-pos',
                    'title' => ['es' => 'Devoluciones', 'en' => 'Returns'],
                    'icon' => 'ti tabler-arrow-back-up',
                    'route' => 'erp.pos.returns.index',
                    'permission' => 'erp.sales.view',
                ],
            ],
        ],
        [
            'key' => 'atencion-cliente',
            'title' => ['es' => 'Atencion al Cliente', 'en' => 'Customer Service'],
            'icon' => 'ti tabler-headset',
            'permission' => 'access.erp',
            'children' => [
                [
                    'key' => 'tickets',
                    'title' => ['es' => 'Tickets', 'en' => 'Tickets'],
                    'icon' => 'ti tabler-search',
                    'route' => 'erp.tickets.index',
                    'permission' => 'access.erp',
                ],
                [
                    'key' => 'recetas-atencion',
                    'title' => ['es' => 'Recetas', 'en' => 'Prescriptions'],
                    'icon' => 'ti tabler-file-certificate',
                    'route' => 'erp.customer-care.prescriptions.index',
                    'permission' => 'access.erp',
                ],
                [
                    'key' => 'cotizaciones-atencion',
                    'title' => ['es' => 'Cotizaciones', 'en' => 'Quotations'],
                    'icon' => 'ti tabler-file-invoice',
                    'route' => 'erp.customer-care.quotes.index',
                    'permission' => 'access.erp',
                ],
                [
                    'key' => 'ordenes-trabajo-atencion',
                    'title' => ['es' => 'Ordenes de Trabajo', 'en' => 'Work Orders'],
                    'icon' => 'ti tabler-clipboard-list',
                    'route' => 'erp.work-orders.index',
                    'permission' => 'access.erp',
                ],
                [
                    'key' => 'ordenes-servicio-atencion',
                    'title' => ['es' => 'Ordenes de Servicio', 'en' => 'Service Orders'],
                    'icon' => 'ti tabler-tool',
                    'route' => 'erp.customer-care.service-orders.index',
                    'permission' => 'access.erp',
                ],
                [
                    'key' => 'cobranza-atencion',
                    'title' => ['es' => 'Cobranza', 'en' => 'Collections'],
                    'icon' => 'ti tabler-credit-card-pay',
                    'route' => 'erp.customer-care.collections.index',
                    'permission' => 'access.erp',
                ],
                [
                    'key' => 'cierre-diario-atencion',
                    'title' => ['es' => 'Cierre diario', 'en' => 'Daily Closing'],
                    'icon' => 'ti tabler-calendar-check',
                    'route' => 'erp.customer-care.daily-closing.index',
                    'permission' => 'access.erp',
                ],
            ],
        ],
        // [
        //     'key' => 'work-orders',
        //     'title' => ['es' => 'Ordenes de Trabajo', 'en' => 'Work Orders'],
        //     'icon' => 'ti tabler-clipboard-list',
        //     'permission' => 'access.erp',
        //     'children' => [
        //         [
        //             'key' => 'nueva-orden',
        //             'title' => ['es' => 'Nueva orden', 'en' => 'New Work Order'],
        //             'icon' => 'ti tabler-file-plus',
        //             'route' => 'erp.work-orders.create',
        //             'permission' => 'access.erp',
        //         ],
        //         [
        //             'key' => 'lista-ordenes',
        //             'title' => ['es' => 'Lista de ordenes', 'en' => 'Work Order List'],
        //             'icon' => 'ti tabler-list',
        //             'route' => 'erp.work-orders.index',
        //             'permission' => 'access.erp',
        //         ],
        //         [
        //             'key' => 'seguimiento-kanban',
        //             'title' => ['es' => 'Seguimiento / Kanban', 'en' => 'Tracking / Kanban'],
        //             'icon' => 'ti tabler-layout-kanban',
        //             'route' => 'erp.work-orders.kanban',
        //             'permission' => 'access.erp',
        //         ],
        //         [
        //             'key' => 'entrega-orden',
        //             'title' => ['es' => 'Entrega de orden', 'en' => 'Work Order Delivery'],
        //             'icon' => 'ti tabler-package-export',
        //             'route' => 'erp.work-orders.delivery.index',
        //             'permission' => 'access.erp',
        //         ],
        //     ],
        // ],
        [
            'key' => 'optometry',
            'title' => ['es' => 'Optometria', 'en' => 'Optometry'],
            'icon' => 'ti tabler-eye',
            'permission' => 'access.erp',
            'children' => [
                [
                    'key' => 'citas-agenda',
                    'title' => ['es' => 'Citas / Agenda', 'en' => 'Appointments / Schedule'],
                    'icon' => 'ti tabler-calendar-event',
                    'route' => 'erp.optometry.appointments.index',
                    'permission' => 'access.erp',
                ],
                [
                    'key' => 'examenes-visuales',
                    'title' => ['es' => 'Examenes visuales', 'en' => 'Visual Exams'],
                    'icon' => 'ti tabler-stethoscope',
                    'route' => 'erp.optometry.exams.index',
                    'permission' => 'access.erp',
                ],
                [
                    'key' => 'historial-paciente',
                    'title' => ['es' => 'Historial del paciente', 'en' => 'Patient History'],
                    'icon' => 'ti tabler-notes',
                    'route' => 'erp.optometry.patients.history',
                    'permission' => 'access.erp',
                ],
                [
                    'key' => 'recetas-emitidas',
                    'title' => ['es' => 'Recetas emitidas', 'en' => 'Issued Prescriptions'],
                    'icon' => 'ti tabler-file-certificate',
                    'route' => 'erp.optometry.prescriptions.index',
                    'permission' => 'access.erp',
                ],
            ],
        ],
        // [
        //     'key' => 'laboratory',
        //     'title' => ['es' => 'Laboratorio (Produccion)', 'en' => 'Laboratory (Production)'],
        //     'icon' => 'ti tabler-flask',
        //     'permission' => 'access.erp',
        //     'children' => [
        //         [
        //             'key' => 'ordenes-laboratorio',
        //             'title' => ['es' => 'Ordenes de laboratorio', 'en' => 'Laboratory Orders'],
        //             'icon' => 'ti tabler-microscope',
        //             'route' => 'erp.laboratory.orders.index',
        //             'permission' => 'access.erp',
        //         ],
        //         [
        //             'key' => 'cola-produccion',
        //             'title' => ['es' => 'Cola de produccion', 'en' => 'Production Queue'],
        //             'icon' => 'ti tabler-list-details',
        //             'route' => 'erp.laboratory.queue.index',
        //             'permission' => 'access.erp',
        //         ],
        //         [
        //             'key' => 'control-calidad',
        //             'title' => ['es' => 'Control de calidad', 'en' => 'Quality Control'],
        //             'icon' => 'ti tabler-checkup-list',
        //             'route' => 'erp.laboratory.quality.index',
        //             'permission' => 'access.erp',
        //         ],
        //         [
        //             'key' => 'materiales-consumidos',
        //             'title' => ['es' => 'Materiales consumidos', 'en' => 'Consumed Materials'],
        //             'icon' => 'ti tabler-packages',
        //             'route' => 'erp.laboratory.materials.index',
        //             'permission' => 'access.erp',
        //         ],
        //     ],
        // ],
        [
            'key' => 'purchases',
            'title' => ['es' => 'Compras', 'en' => 'Purchases'],
            'icon' => 'ti tabler-truck',
            'permission' => 'erp.purchases.view',
            'children' => [
                [
                    'key' => 'solicitudes-compra',
                    'title' => ['es' => 'Solicitudes de compra', 'en' => 'Purchase Requests'],
                    'icon' => 'ti tabler-file-text',
                    'route' => 'erp.purchases.requests.index',
                    'permission' => 'erp.purchases.view',
                ],
                [
                    'key' => 'ordenes-compra',
                    'title' => ['es' => 'Ordenes de compra', 'en' => 'Purchase Orders'],
                    'icon' => 'ti tabler-clipboard-check',
                    'route' => 'erp.purchases.orders.index',
                    'permission' => 'erp.purchases.view',
                ],
                [
                    'key' => 'recepcion-mercaderia',
                    'title' => ['es' => 'Recepcion de mercaderia', 'en' => 'Goods Receipt'],
                    'icon' => 'ti tabler-box-seam',
                    'route' => 'erp.purchases.receipts.index',
                    'permission' => 'erp.purchases.view',
                ],
                [
                    'key' => 'devoluciones-proveedor',
                    'title' => ['es' => 'Devoluciones a proveedor', 'en' => 'Supplier Returns'],
                    'icon' => 'ti tabler-arrow-back-up',
                    'route' => 'erp.purchases.returns.index',
                    'permission' => 'erp.purchases.view',
                ],
                [
                    'key' => 'registro-proveedores',
                    'title' => ['es' => 'Registro de proveedores', 'en' => 'Supplier Registry'],
                    'icon' => 'ti tabler-building-store',
                    'route' => 'partners.proveedores.index',
                    'permission' => 'partners.proveedores.view',
                ],
            ],
        ],
        [
            'key' => 'inventory',
            'title' => ['es' => 'Inventarios', 'en' => 'Inventory'],
            'icon' => 'ti tabler-package',
            'permission' => 'erp.inventory.view',
            'children' => [
                [
                    'key' => 'catalogo-productos',
                    'title' => ['es' => 'Catalogo de productos', 'en' => 'Product Catalog'],
                    'icon' => 'ti tabler-tags',
                    'route' => 'erp.catalogos.index',
                    'permission' => 'erp.inventory.view',
                ],
                [
                    'key' => 'almacenes',
                    'title' => ['es' => 'Almacenes', 'en' => 'Warehouses'],
                    'icon' => 'ti tabler-warehouse',
                    'route' => 'erp.inventory.warehouses.index',
                    'permission' => 'erp.inventory.view',
                ],
                [
                    'key' => 'stock-tiempo-real',
                    'title' => ['es' => 'Stock en tiempo real', 'en' => 'Real-time Stock'],
                    'icon' => 'ti tabler-activity',
                    'route' => 'erp.inventory.stock.index',
                    'permission' => 'erp.inventory.view',
                ],
                [
                    'key' => 'movimientos-inventario',
                    'title' => ['es' => 'Movimientos de inventario', 'en' => 'Inventory Movements'],
                    'icon' => 'ti tabler-arrows-transfer-up-down',
                    'route' => 'erp.inventory.movements.index',
                    'permission' => 'erp.inventory.view',
                ],
                [
                    'key' => 'transferencias-almacenes',
                    'title' => ['es' => 'Transferencias entre almacenes', 'en' => 'Warehouse Transfers'],
                    'icon' => 'ti tabler-route',
                    'route' => 'erp.inventory.transfers.index',
                    'permission' => 'erp.inventory.view',
                ],
                [
                    'key' => 'lotes-series',
                    'title' => ['es' => 'Lotes y series', 'en' => 'Lots and Serials'],
                    'icon' => 'ti tabler-barcode',
                    'route' => 'erp.inventory.lots.index',
                    'permission' => 'erp.inventory.view',
                ],
                [
                    'key' => 'conteo-fisico',
                    'title' => ['es' => 'Conteo fisico / Inventario', 'en' => 'Physical Count / Inventory'],
                    'icon' => 'ti tabler-clipboard-data',
                    'route' => 'erp.inventory.counts.index',
                    'permission' => 'erp.inventory.view',
                ],
                [
                    'key' => 'valorizacion-stock',
                    'title' => ['es' => 'Valorizacion de stock', 'en' => 'Stock Valuation'],
                    'icon' => 'ti tabler-coins',
                    'route' => 'erp.inventory.valuation.index',
                    'permission' => 'erp.inventory.view',
                ],
            ],
        ],
        [
            'key' => 'sales',
            'title' => ['es' => 'Ventas', 'en' => 'Sales'],
            'icon' => 'ti tabler-shopping-cart',
            'permission' => 'erp.sales.view',
            'children' => [
                [
                    'key' => 'clientes',
                    'title' => ['es' => 'Clientes', 'en' => 'Customers'],
                    'icon' => 'ti tabler-user-check',
                    'route' => 'partners.clientes.index',
                    'permission' => 'partners.clientes.view',
                ],
                [
                    'key' => 'cotizaciones',
                    'title' => ['es' => 'Cotizaciones', 'en' => 'Quotations'],
                    'icon' => 'ti tabler-file-invoice',
                    'route' => 'erp.sales.quotes.index',
                    'permission' => 'erp.sales.view',
                ],
                [
                    'key' => 'ordenes-venta',
                    'title' => ['es' => 'Ordenes de venta', 'en' => 'Sales Orders'],
                    'icon' => 'ti tabler-clipboard-check',
                    'route' => 'erp.sales.orders.index',
                    'permission' => 'erp.sales.view',
                ],
                [
                    'key' => 'comprobantes',
                    'title' => ['es' => 'Comprobantes', 'en' => 'Vouchers'],
                    'icon' => 'ti tabler-file-description',
                    'route' => 'erp.sales.vouchers.index',
                    'permission' => 'erp.sales.view',
                ],
                [
                    'key' => 'notas-credito',
                    'title' => ['es' => 'Devoluciones / Notas de credito', 'en' => 'Returns / Credit Notes'],
                    'icon' => 'ti tabler-receipt-refund',
                    'route' => 'erp.sales.credit-notes.index',
                    'permission' => 'erp.sales.view',
                ],
                [
                    'key' => 'lista-precios',
                    'title' => ['es' => 'Lista de precios', 'en' => 'Price Lists'],
                    'icon' => 'ti tabler-list-numbers',
                    'route' => 'erp.sales.price-lists.index',
                    'permission' => 'erp.sales.view',
                ],
            ],
        ],
        [
            'key' => 'reports',
            'title' => ['es' => 'Reportes ERP', 'en' => 'ERP Reports'],
            'icon' => 'ti tabler-chart-bar',
            'permission' => 'access.erp',
            'children' => [
                [
                    'key' => 'ventas-periodo',
                    'title' => ['es' => 'Ventas por periodo / local / vendedor', 'en' => 'Sales by Period / Store / Seller'],
                    'icon' => 'ti tabler-chart-line',
                    'route' => 'erp.reports.sales.index',
                    'permission' => 'access.erp',
                ],
                [
                    'key' => 'ordenes-estado',
                    'title' => ['es' => 'Ordenes de trabajo por estado', 'en' => 'Work Orders by Status'],
                    'icon' => 'ti tabler-list-check',
                    'route' => 'erp.reports.work-orders.index',
                    'permission' => 'access.erp',
                ],
                [
                    'key' => 'produccion-laboratorio',
                    'title' => ['es' => 'Produccion de laboratorio', 'en' => 'Laboratory Production'],
                    'icon' => 'ti tabler-flask-2',
                    'route' => 'erp.reports.laboratory.index',
                    'permission' => 'access.erp',
                ],
                [
                    'key' => 'movimientos-inv-reporte',
                    'title' => ['es' => 'Movimientos de inventario', 'en' => 'Inventory Movements'],
                    'icon' => 'ti tabler-arrows-shuffle',
                    'route' => 'erp.reports.inventory-movements.index',
                    'permission' => 'access.erp',
                ],
                [
                    'key' => 'stock-valorizado',
                    'title' => ['es' => 'Stock valorizado', 'en' => 'Valued Stock'],
                    'icon' => 'ti tabler-currency-dollar',
                    'route' => 'erp.reports.valued-stock.index',
                    'permission' => 'access.erp',
                ],
                [
                    'key' => 'cierres-caja',
                    'title' => ['es' => 'Cierres de caja', 'en' => 'Cash Closings'],
                    'icon' => 'ti tabler-cash-banknote',
                    'route' => 'erp.reports.cash-closures.index',
                    'permission' => 'access.erp',
                ],
                [
                    'key' => 'ranking-productos',
                    'title' => ['es' => 'Ranking de productos', 'en' => 'Product Ranking'],
                    'icon' => 'ti tabler-trophy',
                    'route' => 'erp.reports.product-ranking.index',
                    'permission' => 'access.erp',
                ],
            ],
        ],
        [
            'key' => 'settings',
            'title' => ['es' => 'Configuracion ERP', 'en' => 'ERP Settings'],
            'icon' => 'ti tabler-settings',
            'permission' => 'access.erp',
            'children' => [
                [
                    'key' => 'empresas-locales',
                    'title' => ['es' => 'Empresas y locales', 'en' => 'Companies and Locations'],
                    'icon' => 'ti tabler-building-community',
                    'route' => 'core.companies.index',
                    'permission' => 'core.companies.view',
                ],
                [
                    'key' => 'series-comprobantes',
                    'title' => ['es' => 'Series de comprobantes', 'en' => 'Voucher Series'],
                    'icon' => 'ti tabler-number',
                    'route' => 'erp.settings.voucher-series.index',
                    'permission' => 'access.erp',
                ],
                [
                    'key' => 'tipos-lentes-materiales',
                    'title' => ['es' => 'Tipos de lentes / materiales / tratamientos', 'en' => 'Lens / Material / Treatment Types'],
                    'icon' => 'ti tabler-glasses',
                    'route' => 'erp.settings.optical-catalogs.index',
                    'permission' => 'access.erp',
                ],
                [
                    'key' => 'motivos-movimiento',
                    'title' => ['es' => 'Motivos de movimiento de inventario', 'en' => 'Inventory Movement Reasons'],
                    'icon' => 'ti tabler-arrows-diff',
                    'route' => 'erp.settings.inventory-movement-reasons.index',
                    'permission' => 'access.erp',
                ],
                [
                    'key' => 'parametros-caja',
                    'title' => ['es' => 'Parametros de caja', 'en' => 'Cash Parameters'],
                    'icon' => 'ti tabler-adjustments',
                    'route' => 'erp.settings.cash.index',
                    'permission' => 'access.erp',
                ],
                [
                    'key' => 'impresoras-pos',
                    'title' => ['es' => 'Impresoras y perifericos POS', 'en' => 'POS Printers and Peripherals'],
                    'icon' => 'ti tabler-printer',
                    'route' => 'erp.settings.pos-devices.index',
                    'permission' => 'access.erp',
                ],
            ],
        ],
    ],
];
